"""add stock balances requisitions and adjustments

Revision ID: a035f63c7693
Revises: 3f0264c916e4
Create Date: 2026-09-09 20:35:37.547132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a035f63c7693'
down_revision: Union[str, None] = '3f0264c916e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('charge_item_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Enum('STORE', 'PHARMACY', name='stocklocation'), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('adjusted_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adjusted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['charge_item_id'], ['charge_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_item_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Enum('STORE', 'PHARMACY', name='stocklocation'), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['charge_item_id'], ['charge_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charge_item_id', 'location', name='uq_stock_balance_item_location')
    )
    op.create_table('stock_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('requisition_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'CANCELLED', name='stockrequisitionstatus'), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_number')
    )
    op.create_table('stock_requisition_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('charge_item_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['charge_item_id'], ['charge_items.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['stock_requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Whatever quantity_on_hand held becomes Store's opening balance — that
    # field was filled exclusively by purchase-order receipts, i.e. goods
    # coming in from suppliers, which is Store's job. Pharmacy starts at zero
    # and must requisition stock from Store before it can dispense anything.
    op.execute(
        """
        INSERT INTO stock_balances (charge_item_id, location, quantity_on_hand, created_at, updated_at)
        SELECT id, 'STORE', quantity_on_hand, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM charge_items
        WHERE quantity_on_hand IS NOT NULL AND quantity_on_hand <> 0
        """
    )
    op.drop_column('charge_items', 'quantity_on_hand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_items', sa.Column('quantity_on_hand', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'"), nullable=False))
    op.execute(
        """
        UPDATE charge_items
        SET quantity_on_hand = (
            SELECT COALESCE(SUM(quantity_on_hand), 0) FROM stock_balances WHERE stock_balances.charge_item_id = charge_items.id
        )
        """
    )
    op.drop_table('stock_requisition_lines')
    op.drop_table('stock_requisitions')
    op.drop_table('stock_balances')
    op.drop_table('stock_adjustments')
    # ### end Alembic commands ###
