"""add is_main to branches

Revision ID: c80f90df074a
Revises: aed0abb2d748
Create Date: 2026-08-29 13:49:08.086510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c80f90df074a'
down_revision: Union[str, None] = 'aed0abb2d748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('is_main', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'is_main')
    # ### end Alembic commands ###
